apiVersion: apps/v1
kind: Deployment
metadata:
  name: mpi-cluster
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mpi-cluster
  template:
    metadata:
      labels:
        app: mpi-cluster
    spec:
      containers:
      - name: my-pod
        image: tcfsh22215/my-mpi-image
        #image: tensorflow/tensorflow
        command: ["/bin/bash"]
        volumeMounts:
        - mountPath: /nfs_shared
          #name: nfs-volume
          name: host-volume
      volumes:
      #- name: nfs-volume
      #  nfs:
      #    path: /nfs/general/mpi_cluster_shared
      #    server: 140.96.154.21
      - name: host-volume
        hostPath:
          path: /home/K8S/tcfsh/mpi_cluster
